In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
dataset=pd.read_csv("/kaggle/input/datasets/organizations/uciml/sms-spam-collection-dataset/spam.csv",encoding='latin-1')

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/datasets/organizations/uciml/sms-spam-collection-dataset/spam.csv'

In [ ]:
dataset.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [ ]:
dataset=dataset.drop(columns=["Unnamed: 2","Unnamed: 3","Unnamed: 4"])

In [ ]:
dataset.head(5)

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
dataset["v2"][0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [ ]:
#remove punctuations, remove links, remove words with text,remove words in brackets
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   v1      5572 non-null   object
 1   v2      5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset['targed_encoded']=le.fit_transform(dataset['v1'])
dataset.head(5)

     v1                                                 v2  targed_encoded
0   ham  Go until jurong point, crazy.. Available only ...               0
1   ham                      Ok lar... Joking wif u oni...               0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...               1
3   ham  U dun say so early hor... U c already then say...               0
4   ham  Nah I don't think he goes to usf, he lives aro...               0

In [ ]:
import re
import string
def clean_text(text):
    '''Make text lowercase, remove text in square brackets,remove links,remove punctuation
    and remove words containing numbers.'''
    text = str(text).lower()
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'<.*?>+', '', text)
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub(r'\n', '', text)
    text = re.sub(r'\w*\d\w*', '', text)
    return text

In [ ]:
dataset["clean message"]=dataset["v2"].apply(clean_text)

In [ ]:
dataset.head(5)

,v1,v2,targed_encoded,clean message
0,ham,"Go until jurong point, crazy.. Available only ...",0,go until jurong point crazy available only in ...
1,ham,Ok lar... Joking wif u oni...,0,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1,free entry in a wkly comp to win fa cup final...
3,ham,U dun say so early hor... U c already then say...,0,u dun say so early hor u c already then say
4,ham,"Nah I don't think he goes to usf, he lives aro...",0,nah i dont think he goes to usf he lives aroun...

In [ ]:
from nltk.corpus import stopwords
stopword=stopwords.words('english')

In [ ]:
def remove_stopwords(text):
    text=' '.join(word for word in text.split(' ') if word not in stopword)
    return text

In [ ]:
dataset["clean message"]= dataset["clean message"].apply(remove_stopwords)

In [ ]:
dataset.head(5)

,v1,v2,targed_encoded,clean message
0,ham,"Go until jurong point, crazy.. Available only ...",0,go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,0,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1,free entry wkly comp win fa cup final tkts m...
3,ham,U dun say so early hor... U c already then say...,0,u dun say early hor u c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",0,nah dont think goes usf lives around though

In [ ]:
#Stemming 
from nltk.stem import SnowballStemmer
stemmer=SnowballStemmer('english')

In [ ]:
def stemming(text):
    text=' '.join(stemmer.stem(word) for word in text.split(' '))
    return text

In [ ]:
dataset["clean message"].apply(stemming)

0       go jurong point crazi avail bugi n great world...
1                                   ok lar joke wif u oni
2       free entri  wkli comp win fa cup final tkts  m...
3                     u dun say earli hor u c alreadi say
4               nah dont think goe usf live around though
                              ...
5567     time tri  contact u u å£ pound prize  claim e...
5568                              ì b go esplanad fr home
5569                             piti  mood soani suggest
5570    guy bitch act like id interest buy someth els ...
5571                                       rofl true name
Name: clean message, Length: 5572, dtype: object

In [ ]:
dataset.head(5)

,v1,v2,targed_encoded,clean message
0,ham,"Go until jurong point, crazy.. Available only ...",0,go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,0,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1,free entry wkly comp win fa cup final tkts m...
3,ham,U dun say so early hor... U c already then say...,0,u dun say early hor u c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",0,nah dont think goes usf lives around though

In [ ]:
X=dataset["clean message"].copy()
y=dataset["targed_encoded"].copy()
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4179,)
(1393,)
(4179,)
(1393,)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(ngram_range=(1,2),stop_words='english',min_df=5,max_df=0.8)
x_train_tfidf=tfidf.fit_transform(X_train)

In [ ]:
x_train_tfidf

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 23282 stored elements and shape (4179, 1441)>

In [ ]:
sum(y_train)/len(y_train)

0.13304618329743959

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
lr_model=LogisticRegression()
lr_model.fit(x_train_tfidf,y_train)
x_test_tfidf=tfidf.transform(X_test)
logr_predict=lr_model.predict(x_test_tfidf)

In [ ]:
from sklearn import metrics
print(metrics.accuracy_score(y_test,logr_predict))
print(metrics.confusion_matrix(y_test,logr_predict))

0.9547738693467337
[[1199    3]
 [  60  131]]

In [ ]:
print(metrics.f1_score(y_test,logr_predict))

0.8061538461538461

In [ ]:
from sklearn.naive_bayes import MultinomialNB
naive_bayes=MultinomialNB()
naive_bayes.fit(x_train_tfidf,y_train)
nb_predict=naive_bayes.predict(x_test_tfidf)
print(metrics.f1_score(nb_predict,y_test))

0.8786127167630058

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rnd_clf=RandomForestClassifier(random_state=42,n_jobs=-1)
rnd_clf.fit(x_train_tfidf,y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [ ]:
print(metrics.f1_score(rnd_clf.predict(x_train_tfidf),y_train))
print(metrics.f1_score(rnd_clf.predict(x_test_tfidf),y_test))

0.9963963963963964
0.895774647887324

In [ ]:
rnd_clf_2=RandomForestClassifier(random_state=42,n_jobs=-1,n_estimators=50,max_depth=80)
rnd_clf_2.fit(x_train_tfidf,y_train)

RandomForestClassifier(max_depth=80, n_estimators=50, n_jobs=-1,
                       random_state=42)

In [ ]:
print(metrics.f1_score(rnd_clf_2.predict(x_train_tfidf),y_train))
print(metrics.f1_score(rnd_clf_2.predict(x_test_tfidf),y_test))

0.9891107078039928
0.9014084507042254

In [ ]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(x_train_tfidf,y_train)

SVC()

In [ ]:
print(metrics.f1_score(svc.predict(x_train_tfidf),y_train))
print(metrics.f1_score(svc.predict(x_test_tfidf),y_test))

0.979890310786106
0.9065155807365439

In [ ]:
from xgboost import XGBClassifier
clf_xgb = XGBClassifier(
    objective='binary:logistic',
    seed=42,
    early_stopping_rounds=10,
    eval_metric='aucpr'
)
clf_xgb.fit(x_train_tfidf,y_train,eval_set=[(x_test_tfidf,y_test)],verbose=True,)

[0]	validation_0-aucpr:0.66388
[1]	validation_0-aucpr:0.73701
[2]	validation_0-aucpr:0.77906
[3]	validation_0-aucpr:0.80751
[4]	validation_0-aucpr:0.82706
[5]	validation_0-aucpr:0.83246
[6]	validation_0-aucpr:0.85249
[7]	validation_0-aucpr:0.85614
[8]	validation_0-aucpr:0.86143
[9]	validation_0-aucpr:0.86477
[10]	validation_0-aucpr:0.86803
[11]	validation_0-aucpr:0.87339
[12]	validation_0-aucpr:0.87642
[13]	validation_0-aucpr:0.87747
[14]	validation_0-aucpr:0.88300
[15]	validation_0-aucpr:0.88660
[16]	validation_0-aucpr:0.88892
[17]	validation_0-aucpr:0.89185
[18]	validation_0-aucpr:0.89251
[19]	validation_0-aucpr:0.89389
[20]	validation_0-aucpr:0.89518
[21]	validation_0-aucpr:0.89756
[22]	validation_0-aucpr:0.89888
[23]	validation_0-aucpr:0.89967
[24]	validation_0-aucpr:0.89942
[25]	validation_0-aucpr:0.90072
[26]	validation_0-aucpr:0.90148
[27]	validation_0-aucpr:0.90233
[28]	validation_0-aucpr:0.90415
[29]	validation_0-aucpr:0.90435
[30]	validation_0-aucpr:0.90530
[31]	validation_0-aucpr:0.90569
[32]	validation_0-aucpr:0.90636
[33]	validation_0-aucpr:0.90730
[34]	validation_0-aucpr:0.90752
[35]	validation_0-aucpr:0.90783
[36]	validation_0-aucpr:0.90734
[37]	validation_0-aucpr:0.90868
[38]	validation_0-aucpr:0.90860
[39]	validation_0-aucpr:0.90848
[40]	validation_0-aucpr:0.90811
[41]	validation_0-aucpr:0.90776
[42]	validation_0-aucpr:0.90756
[43]	validation_0-aucpr:0.90823
[44]	validation_0-aucpr:0.90916
[45]	validation_0-aucpr:0.90968
[46]	validation_0-aucpr:0.90961
[47]	validation_0-aucpr:0.90962
[48]	validation_0-aucpr:0.90956
[49]	validation_0-aucpr:0.90935
[50]	validation_0-aucpr:0.90937
[51]	validation_0-aucpr:0.90949
[52]	validation_0-aucpr:0.91013
[53]	validation_0-aucpr:0.91052
[54]	validation_0-aucpr:0.91114
[55]	validation_0-aucpr:0.91043
[56]	validation_0-aucpr:0.91054
[57]	validation_0-aucpr:0.91039
[58]	validation_0-aucpr:0.91039
[59]	validation_0-aucpr:0.91077
[60]	validation_0-aucpr:0.91070
[61]	validation_0-aucpr:0.91113
[62]	validation_0-aucpr:0.91097
[63]	validation_0-aucpr:0.91040
[64]	validation_0-aucpr:0.91145
[65]	validation_0-aucpr:0.91193
[66]	validation_0-aucpr:0.91202
[67]	validation_0-aucpr:0.91216
[68]	validation_0-aucpr:0.91228
[69]	validation_0-aucpr:0.91211
[70]	validation_0-aucpr:0.91243
[71]	validation_0-aucpr:0.91252
[72]	validation_0-aucpr:0.91397
[73]	validation_0-aucpr:0.91426
[74]	validation_0-aucpr:0.91430
[75]	validation_0-aucpr:0.91447
[76]	validation_0-aucpr:0.91438
[77]	validation_0-aucpr:0.91421
[78]	validation_0-aucpr:0.91406
[79]	validation_0-aucpr:0.91368
[80]	validation_0-aucpr:0.91387
[81]	validation_0-aucpr:0.91423
[82]	validation_0-aucpr:0.91421
[83]	validation_0-aucpr:0.91419
[84]	validation_0-aucpr:0.91439
[85]	validation_0-aucpr:0.91535
[86]	validation_0-aucpr:0.91562
[87]	validation_0-aucpr:0.91551
[88]	validation_0-aucpr:0.91542
[89]	validation_0-aucpr:0.91581
[90]	validation_0-aucpr:0.91561
[91]	validation_0-aucpr:0.91508
[92]	validation_0-aucpr:0.91544
[93]	validation_0-aucpr:0.91590
[94]	validation_0-aucpr:0.91624
[95]	validation_0-aucpr:0.91631
[96]	validation_0-aucpr:0.91612
[97]	validation_0-aucpr:0.91642
[98]	validation_0-aucpr:0.91597
[99]	validation_0-aucpr:0.91629

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=10,
              enable_categorical=False, eval_metric='aucpr', feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
print(metrics.f1_score(clf_xgb.predict(x_train_tfidf),y_train))
print(metrics.f1_score(clf_xgb.predict(x_test_tfidf),y_test))

0.9452830188679245
0.8488372093023255

In [ ]:
print(metrics.accuracy_score(clf_xgb.predict(x_test_tfidf),y_test))

0.9626704953338119

In [ ]:
print(metrics.accuracy_score(naive_bayes.predict(x_test_tfidf),y_test))

0.9698492462311558

In [ ]:
print(metrics.accuracy_score(svc.predict(x_test_tfidf),y_test))
print(metrics.confusion_matrix(svc.predict(x_test_tfidf),y_test))

0.9763101220387652
[[1200   31]
 [   2  160]]

In [ ]:
metrics.recall_score(svc.predict(x_test_tfidf),y_test)

0.9876543209876543

In [ ]:
import joblib
joblib.dump(model,'spam_classifier_model.pkl')